### ISSUE TITLE
Unable to display progress for tag, company and total.

### ISSUE THREAD

**Issue by csujedihy** [binarylu/leetcode-ext#6]

**Comment by Brian-0114** [comment]
same here

**Comment by binarylu** [comment]
fixing.
Thank you both.

**Comment by binarylu** [comment]
bug has been fixed. It's a urgent fix, please let me know if you still meet bugs.  
Thank you so much.

**Comment by csujedihy** [comment]
The total progress can be displayed now but progress over different companies and tags still cannot be displayed.

**Comment by csujedihy** [comment]
By total progress, I mean the bar chart at the bottom of the right column.

**Comment by csujedihy** [comment]
It works!
